# Generated by Django 4.1.1 on 2022-11-19 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_order_defect_order_diagnostic_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finally_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
