# Generated by Django 4.1.1 on 2022-11-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='main_app.brand'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(default='No brand', max_length=40),
        ),
    ]
