# Generated by Django 4.1.3 on 2022-12-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_unittype_order_unit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='unit_type',
            new_name='type_of_unit',
        ),
    ]
