# Generated by Django 4.1.3 on 2022-12-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_rename_type_unittype_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(default='No brand', max_length=40, unique=True, verbose_name='Бренд'),
        ),
    ]
