# Generated by Django 4.1.4 on 2022-12-25 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_alter_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='main_app.unittype', verbose_name='Type'),
        ),
    ]
