# Generated by Django 4.1.4 on 2022-12-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='main_app.unittype', verbose_name='Unit type'),
        ),
    ]
