# Generated by Django 4.1.4 on 2022-12-26 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_alter_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='type_of_unit',
        ),
    ]
