# Generated by Django 4.1.4 on 2023-01-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='part',
            field=models.ManyToManyField(to='main_app.part'),
        ),
    ]
