# Generated by Django 4.1.4 on 2023-01-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_unit_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='part',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.part'),
        ),
    ]
