# Generated by Django 4.1.4 on 2023-01-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_services_price_alter_unit_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
