# Generated by Django 4.1.1 on 2022-11-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_model_remove_order_brand_unit_order_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='serial_number',
            field=models.CharField(default='No serial', max_length=42),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(default='No brand', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
