# Generated by Django 4.1.1 on 2022-11-19 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_unit_serial_number_alter_brand_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(default='No brand', max_length=40, unique=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=40, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(max_length=40, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model',
            field=models.CharField(max_length=40, unique=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='main_app.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='defect',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Описание дефекта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='diagnostic_result',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Результат диагностики'),
        ),
        migrations.AlterField(
            model_name='order',
            name='finally_price',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма ремонта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='main_app.unit', verbose_name='Техника'),
        ),
        migrations.AlterField(
            model_name='order',
            name='works',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Выполненные работы'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='main_app.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='main_app.model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='serial_number',
            field=models.CharField(default='No serial', max_length=42, verbose_name='Серийный номер'),
        ),
    ]
