# Generated by Django 4.1.3 on 2022-12-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_order_repair_stage_alter_repairstage_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(default='No brand', max_length=40, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model',
            field=models.CharField(max_length=40, verbose_name='Модель'),
        ),
    ]
