# Generated by Django 4.1.3 on 2022-11-30 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_order_repair_stage_alter_repairstage_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='main_app.client', verbose_name='Клиент'),
        ),
    ]
