# Generated by Django 4.1.3 on 2022-12-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_brand_brand_alter_model_model'),
        ('main_app', '0017_alter_order_client'),
    ]

    operations = [
    ]
