# Generated by Django 4.1.3 on 2022-12-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_merge_20221201_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=28)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='unit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='main_app.unittype', verbose_name='Тип устройства'),
        ),
    ]
