# Generated by Django 4.1.3 on 2022-12-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_rename_unit_type_order_type_of_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unittype',
            old_name='type',
            new_name='unit_type',
        ),
    ]
