# Generated by Django 4.1.3 on 2022-12-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_brand_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(default='No brand', max_length=40, verbose_name='Бренд'),
        ),
    ]
