# Generated by Django 4.1.3 on 2022-12-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_brand_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model',
            field=models.CharField(default='No model', max_length=40, verbose_name='Модель'),
        ),
    ]
