# Generated by Django 4.1.3 on 2022-12-03 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model',
            field=models.CharField(default='No model', max_length=40, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='main_app.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='defect',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Defect description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='diagnostic_result',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Diagnostic result'),
        ),
        migrations.AlterField(
            model_name='order',
            name='finally_price',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='repair_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='main_app.repairstage', verbose_name='Repair stage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='main_app.unittype', verbose_name='Unit type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='main_app.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='order',
            name='works',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='completed work'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='main_app.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='main_app.model', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='serial_number',
            field=models.CharField(default='No serial', max_length=42, verbose_name='Serial number'),
        ),
    ]
